// Temney Agent v3.0 — server-only orchestrator.
// The model can choose tools, but every tool is dispatched here with verified user ownership.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS", "Content-Type": "application/json" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: cors });
const clip = (value: unknown, max: number) => typeof value === "string" ? value.replace(/\s+/g, " ").trim().slice(0, max) : "";
const CHARACTER_BIBLE = "mysterious solitary figure; street-worn hoodie or worn jacket; urban decay, alley, rooftop, graffiti or chain-link fence; night or dusk; muted desaturated palette with one harsh orange streetlight or cold-blue neon accent; gritty cinematic realism; face never clearly visible, always hood, silhouette, back turned, deep shadow or partial crop; pain shown through posture, clothing and environment, never a clear facial expression; clean negative space in top or bottom third for later overlay; no readable text, logo or watermark";
const CONFIRM_REQUIRED = new Set(["publish_to_youtube", "update_existing_video", "send_comment_reply"]);

type Input = { message?: unknown; history?: unknown; conversationId?: unknown; autoPublish?: unknown };
type ToolCall = { id?: string; function?: { name?: string; arguments?: string } };
type GeminiResponse = { candidates?: Array<{ content?: { parts?: Array<{ text?: string; functionCall?: { name?: string; args?: Record<string, unknown> } }> } }> };
const toolDefs = [
  { name: "list_songs", description: "List the user's songs and their artwork/video readiness.", parameters: { type: "object", properties: { withoutArtwork: { type: "boolean" } } } },
  { name: "extract_lyric_themes", description: "Extract 3-6 visual motifs from a song lyric.", parameters: { type: "object", properties: { songId: { type: "string" } }, required: ["songId"] } },
  { name: "generate_song_artwork", description: "Generate Temney artwork from a song lyric and save it to private storage.", parameters: { type: "object", properties: { songId: { type: "string" }, aspectRatio: { type: "string", enum: ["1:1", "16:9"] }, userNote: { type: "string" } }, required: ["songId"] } },
  { name: "generate_metadata", description: "Draft YouTube title, description and tags for a song. Never publishes.", parameters: { type: "object", properties: { songId: { type: "string" } }, required: ["songId"] } },
  { name: "render_video", description: "Queue a video render from the final song audio and artwork.", parameters: { type: "object", properties: { songId: { type: "string" }, type: { type: "string", enum: ["lyric_video", "static_cover", "short", "teaser"] } }, required: ["songId"] } },
  { name: "create_recommendation", description: "Save a strategic recommendation for the user.", parameters: { type: "object", properties: { category: { type: "string", enum: ["seo", "thumbnail", "schedule", "content", "engagement", "strategy"] }, recommendation: { type: "string" }, reasoning: { type: "string" } }, required: ["category", "recommendation"] } },
  { name: "schedule_publication", description: "Create a private draft publication with a suggested time; never publish.", parameters: { type: "object", properties: { songId: { type: "string" }, title: { type: "string" }, scheduledAt: { type: "string" } }, required: ["songId"] } },
  { name: "publish_to_youtube", description: "Publish an already prepared draft. This always becomes pending confirmation unless the server setting explicitly allows automation.", parameters: { type: "object", properties: { publicationId: { type: "string" } }, required: ["publicationId"] } },
];

function historyFrom(input: Input) {
  if (!Array.isArray(input.history)) return [];
  return input.history.slice(-12).flatMap((entry) => { const item = entry as { role?: unknown; content?: unknown }; const text = clip(item.content, 1500); return text ? [{ role: item.role === "assistant" ? "model" : "user", parts: [{ text }] }] : []; });
}
async function gemini(apiKey: string, system: string, contents: unknown[], tools = true) {
  const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${encodeURIComponent(apiKey)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ systemInstruction: { parts: [{ text: system }] }, contents, tools: tools ? [{ functionDeclarations: toolDefs }] : undefined, generationConfig: { temperature: 0.55, maxOutputTokens: 1200 } }) });
  if (!response.ok) throw new Error(`Gemini request failed (${response.status}): ${(await response.text()).slice(0, 300)}`);
  return await response.json() as GeminiResponse;
}
async function row(admin: any, table: string, id: string, userId: string, select = "*") { const { data, error } = await admin.from(table).select(select).eq("id", id).eq("user_id", userId).maybeSingle(); if (error) throw new Error(error.message); if (!data) throw new Error("Položka nebyla nalezena nebo k ní nemáš přístup."); return data; }
async function log(admin: any, userId: string, action: string, result: "success" | "error" | "pending", payload: unknown, targetId?: string, errorMessage?: string) { await admin.from("agent_action_log").insert({ user_id: userId, action_type: action, target_id: targetId ?? null, payload, result, error_message: errorMessage ?? null }); }
async function dispatch(admin: any, userId: string, name: string, args: Record<string, unknown>, geminiKey: string) {
  if (CONFIRM_REQUIRED.has(name)) { await log(admin, userId, name, "pending", args); return { status: "pending_confirmation", message: `Akce ${name} čeká na potvrzení uživatele. Nic veřejného nebylo provedeno.` }; }
  if (name === "list_songs") { let query = admin.from("sc_songs").select("id,title,cover_path,album_id,created_at,updated_at").eq("user_id", userId).order("updated_at", { ascending: false }).limit(50); const { data, error } = await query; if (error) throw new Error(error.message); const songs = (data ?? []).filter((song: any) => !args.withoutArtwork || !song.cover_path); await log(admin, userId, name, "success", { count: songs.length }); return { status: "success", count: songs.length, songs }; }
  if (name === "extract_lyric_themes") { const song = await row(admin, "sc_songs", String(args.songId), userId, "id,title,lyrics,style_prompt"); const answer = await gemini(geminiKey, `Extract exactly 3-6 concise visual motifs for Temney from the lyric. Return only a JSON array of strings. Character bible: ${CHARACTER_BIBLE}`, [{ role: "user", parts: [{ text: JSON.stringify({ title: song.title, style: song.style_prompt, lyrics: clip(song.lyrics, 5000) }) }] }], false); const text = answer.candidates?.[0]?.content?.parts?.map((part) => part.text ?? "").join("") ?? "[]"; try { const cleaned = text.replace(/^```(?:json)?\s*|\s*```$/g, "").trim(); return { themes: JSON.parse(cleaned) }; } catch { return { themes: [text.slice(0, 240)] }; } }
  if (name === "generate_song_artwork") { const song = await row(admin, "sc_songs", String(args.songId), userId, "id,title,lyrics,style_prompt,album_id"); const ratio = args.aspectRatio === "1:1" ? "1:1" : "16:9"; const prompt = `Temney music artwork, ${ratio} composition. ${CHARACTER_BIBLE}. Song title: ${clip(song.title, 140)}. Mood and lyric atmosphere: ${clip(song.style_prompt, 500)} ${clip(song.lyrics, 2400)}. Creative note: ${clip(args.userNote, 400)}.`; const asset = { user_id: userId, song_id: song.id, asset_type: "song_artwork", aspect_ratio: ratio, prompt_used: prompt, status: "generating" }; const { data: created, error: createError } = await admin.from("agent_image_assets").insert(asset).select("id").single(); if (createError) throw new Error(createError.message); const seed = crypto.randomUUID(); const sourceUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=${ratio === "16:9" ? 1280 : 1024}&height=${ratio === "16:9" ? 720 : 1024}&seed=${encodeURIComponent(seed)}&nologo=true`; const image = await fetch(sourceUrl); if (!image.ok) throw new Error(`Pollinations artwork generation failed (${image.status}).`); const bytes = new Uint8Array(await image.arrayBuffer()); const path = `${userId}/agent-artwork/${song.id}-${seed}.jpg`; const { error: uploadError } = await admin.storage.from("songcraft").upload(path, bytes, { contentType: "image/jpeg", upsert: false }); if (uploadError) throw new Error(uploadError.message); await admin.from("agent_image_assets").update({ base_image_path: path, final_image_path: path, status: "ready", seed }).eq("id", created.id); await admin.from("sc_songs").update({ cover_path: path }).eq("id", song.id).eq("user_id", userId); await log(admin, userId, name, "success", { path, ratio }, song.id); return { status: "ready", assetId: created.id, storagePath: path, prompt }; }
  if (name === "generate_metadata") { const song = await row(admin, "sc_songs", String(args.songId), userId, "id,title,lyrics,style_prompt"); const answer = await gemini(geminiKey, "Create YouTube metadata in Czech for Temney. Return JSON with title (max 100 chars), description (max 4500 chars), tags (array of max 15 short strings). No claims not supported by the input.", [{ role: "user", parts: [{ text: JSON.stringify({ title: song.title, style: song.style_prompt, lyrics: clip(song.lyrics, 2600) }) }] }], false); const text = answer.candidates?.[0]?.content?.parts?.map((part) => part.text ?? "").join("") ?? "{}"; return { draft: text.replace(/^```json\s*|\s*```$/g, "").trim() }; }
  if (name === "render_video") { const song = await row(admin, "sc_songs", String(args.songId), userId, "id,title"); const { data, error } = await admin.from("agent_videos").insert({ user_id: userId, song_id: song.id, type: args.type ?? "static_cover", render_status: "queued" }).select("id,render_status").single(); if (error) throw new Error(error.message); await log(admin, userId, name, "success", { type: args.type ?? "static_cover" }, data.id); return { status: "queued", videoId: data.id }; }
  if (name === "create_recommendation") { const { data, error } = await admin.from("agent_recommendations").insert({ user_id: userId, category: args.category ?? "strategy", recommendation: clip(args.recommendation, 2000), reasoning: clip(args.reasoning, 3000) }).select("id,status").single(); if (error) throw new Error(error.message); await log(admin, userId, name, "success", args, data.id); return data; }
  if (name === "schedule_publication") { const song = await row(admin, "sc_songs", String(args.songId), userId, "id,title,cover_path"); const suggested = typeof args.scheduledAt === "string" && args.scheduledAt ? args.scheduledAt : new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(); const { data, error } = await admin.from("youtube_publications").insert({ user_id: userId, song_id: song.id, title: clip(args.title, 100) || `Temney – ${song.title}`, thumbnail_path: song.cover_path, scheduled_at: suggested, status: "draft", privacy_status: "private" }).select("id,status,scheduled_at").single(); if (error) throw new Error(error.message); await log(admin, userId, name, "success", { scheduledAt: suggested }, data.id); return data; }
  throw new Error(`Neznámý nástroj: ${name}`);
}

Deno.serve(async (request) => {
  try {
    return await handle(request);
  } catch (error) {
    const message = error instanceof Error ? error.stack || error.message : String(error);
    return json({ error: message }, 500);
  }
});

async function handle(request: Request): Promise<Response> {
  if (request.method === "OPTIONS") return new Response("ok", { headers: cors });
  if (request.method !== "POST") return json({ error: "Použij POST." }, 405);
  const authorization = request.headers.get("Authorization"); const url = Deno.env.get("SUPABASE_URL"); const anon = Deno.env.get("SUPABASE_ANON_KEY"); const service = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); const geminiKey = Deno.env.get("GEMINI_API_KEY") || Deno.env.get("GOOGLE_AI_STUDIO_KEY");
  if (!authorization || !url || !anon || !service || !geminiKey) return json({ error: "Agent není nakonfigurovaný. Nastav Supabase secrets GEMINI_API_KEY, SUPABASE_URL a service role klíč." }, 503);
  const auth = createClient(url, anon, { global: { headers: { Authorization: authorization } } }); const { data: { user }, error: authError } = await auth.auth.getUser(); if (authError || !user) return json({ error: "Neplatné přihlášení." }, 401); const admin = createClient(url, service);
  const input = await request.json().catch(() => null) as Input | null; const message = clip(input?.message, 2000); if (!message) return json({ error: "Napiš zprávu pro agenta." }, 400);
  const system = `Jsi Temney Agent v SongCraft Studio. Odpovídej česky. Používej nástroje, když můžeš provést konkrétní bezpečný krok. Nikdy netvrď, že se akce stala, pokud nástroj nevrátil úspěch. Veřejné akce jsou vždy pending_confirmation. Character bible: ${CHARACTER_BIBLE}. Soukromá data patří pouze ověřenému user_id ${user.id}.`;
  const contents: any[] = [...historyFrom(input ?? {}), { role: "user", parts: [{ text: message }] }]; let finalText = ""; const pending: unknown[] = [];
  for (let step = 0; step < 6; step += 1) { const response = await gemini(geminiKey, system, contents, true); const parts = response.candidates?.[0]?.content?.parts ?? []; const calls = parts.map((part) => part.functionCall).filter(Boolean) as Array<{ name?: string; args?: Record<string, unknown> }>; const text = parts.map((part) => part.text ?? "").join("\n").trim(); if (text) finalText = text; if (!calls.length) break; contents.push({ role: "model", parts: parts.filter((part) => part.functionCall) }); for (const call of calls) { const name = call.name ?? ""; try { const result = await dispatch(admin, user.id, name, call.args ?? {}, geminiKey); if ((result as any)?.status === "pending_confirmation") pending.push({ tool: name, ...result }); contents.push({ role: "function", parts: [{ functionResponse: { name, response: result } }] }); } catch (error) { const message = error instanceof Error ? error.message : "Nástroj selhal."; await log(admin, user.id, name, "error", call.args ?? {}, undefined, message); contents.push({ role: "function", parts: [{ functionResponse: { name, response: { error: message } } }] }); } } }
  if (!finalText) finalText = "Úkol jsem zpracoval, ale agent nevrátil textové shrnutí."; if (pending.length) finalText += `\n\nČeká na potvrzení:\n${pending.map((item: any) => `• ${item.tool}`).join("\n")}`;
  return json({ answer: finalText, pending });
}
