import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS", "Content-Type": "application/json" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: cors });
const clip = (v: unknown, n: number) => typeof v === "string" ? v.trim().slice(0, n) : "";
async function signedUrl(url: string, service: string, path: string) { const response = await fetch(`${url}/storage/v1/object/sign/songcraft/${path.split("/").map(encodeURIComponent).join("/")}`, { method: "POST", headers: { apikey: service, Authorization: `Bearer ${service}`, "Content-Type": "application/json" }, body: JSON.stringify({ expiresIn: 900 }) }); if (!response.ok) throw new Error("Video file cannot be signed."); const result = await response.json(); return `${url}/storage/v1${result.signedURL}`; }
async function getAccessToken(admin: any, userId: string, credential: any) {
  if (credential.expires_at && new Date(credential.expires_at).getTime() > Date.now() + 60_000) return credential.access_token;
  const clientId = Deno.env.get("YOUTUBE_CLIENT_ID"); const clientSecret = Deno.env.get("YOUTUBE_CLIENT_SECRET"); if (!clientId || !clientSecret || !credential.refresh_token) throw new Error("YouTube OAuth refresh není nakonfigurovaný.");
  const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: clientId, client_secret: clientSecret, refresh_token: credential.refresh_token, grant_type: "refresh_token" }) }); const token = await response.json().catch(() => null) as { access_token?: string; expires_in?: number; error?: string };
  if (!response.ok || !token.access_token) throw new Error(token.error || "YouTube OAuth refresh selhal."); await admin.from("youtube_credentials").update({ access_token: token.access_token, expires_at: new Date(Date.now() + (token.expires_in ?? 3600) * 1000).toISOString(), updated_at: new Date().toISOString() }).eq("user_id", userId); return token.access_token;
}
Deno.serve(async (request) => {
  if (request.method === "OPTIONS") return new Response("ok", { headers: cors });
  if (request.method !== "POST") return json({ error: "Použij POST." }, 405);
  const authorization = request.headers.get("Authorization"); const url = Deno.env.get("SUPABASE_URL"); const anon = Deno.env.get("SUPABASE_ANON_KEY"); const service = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if (!authorization || !url || !anon || !service) return json({ error: "Chybí bezpečná konfigurace." }, 503);
  const auth = createClient(url, anon, { global: { headers: { Authorization: authorization } } }); const { data: { user } } = await auth.auth.getUser(); if (!user) return json({ error: "Neplatné přihlášení." }, 401); const admin = createClient(url, service);
  const input = await request.json().catch(() => null) as { publicationId?: string; confirm?: boolean } | null; if (!input?.publicationId) return json({ error: "Chybí publicationId." }, 400);
  const { data: publication, error } = await admin.from("youtube_publications").select("*").eq("id", input.publicationId).eq("user_id", user.id).maybeSingle(); if (error || !publication) return json({ error: "Draft publikace nebyl nalezen." }, 404);
  const title = clip(publication.title, 100); const description = clip(publication.description, 5000); const tags = Array.isArray(publication.tags) ? publication.tags.slice(0, 15).map((tag: unknown) => clip(tag, 30)).filter(Boolean) : [];
  if (!title) return json({ error: "Před publikací chybí název videa." }, 400);
  if (!input.confirm) { await admin.from("agent_action_log").insert({ user_id: user.id, action_type: "publish_to_youtube", target_id: publication.id, payload: { title, description, tags }, result: "pending" }); return json({ status: "pending_confirmation", publication: { id: publication.id, title, description, tags, privacyStatus: publication.privacy_status } }); }
  if (publication.status === "published" && publication.youtube_video_id) return json({ status: "published", youtubeVideoId: publication.youtube_video_id });
  if (!publication.video_id) return json({ error: "Draft nemá připravené video. Nejprve spusť render." }, 400);
  const { data: video } = await admin.from("agent_videos").select("id,storage_path,render_status").eq("id", publication.video_id).eq("user_id", user.id).maybeSingle(); if (!video || video.render_status !== "ready" || !video.storage_path) return json({ error: "Video ještě není připravené pro upload." }, 409);
  const { data: credential } = await admin.from("youtube_credentials").select("access_token,refresh_token,expires_at,channel_id").eq("user_id", user.id).maybeSingle(); if (!credential?.access_token && !credential?.refresh_token) return json({ error: "Nejdříve připoj YouTube OAuth účet." }, 412);
  try {
    const accessToken = await getAccessToken(admin, user.id, credential); const fileUrl = await signedUrl(url, service, video.storage_path); const fileResponse = await fetch(fileUrl); if (!fileResponse.ok) throw new Error("Video se nepodařilo stáhnout ze Storage."); const bytes = new Uint8Array(await fileResponse.arrayBuffer());
    const metadata = { snippet: { title, description, tags, categoryId: "10" }, status: { privacyStatus: publication.privacy_status || "private", selfDeclaredMadeForKids: false } };
    const init = await fetch("https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status", { method: "POST", headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json; charset=UTF-8", "X-Upload-Content-Type": "video/mp4", "X-Upload-Content-Length": String(bytes.byteLength) }, body: JSON.stringify(metadata) }); if (!init.ok) throw new Error(`YouTube upload session selhala (${init.status}).`); const location = init.headers.get("location"); if (!location) throw new Error("YouTube nevrátil upload URL.");
    const upload = await fetch(location, { method: "PUT", headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "video/mp4", "Content-Length": String(bytes.byteLength) }, body: bytes }); const result = await upload.json().catch(() => null) as { id?: string; error?: { message?: string } } | null; if (!upload.ok || !result?.id) throw new Error(result?.error?.message || `YouTube upload selhal (${upload.status}).`);
    await admin.from("youtube_publications").update({ status: "published", youtube_video_id: result.id, published_at: new Date().toISOString() }).eq("id", publication.id).eq("user_id", user.id); if (publication.song_id) await admin.from("sc_songs").update({ is_published: true, published_video_id: result.id, published_at: new Date().toISOString() }).eq("id", publication.song_id).eq("user_id", user.id); await admin.from("agent_action_log").insert({ user_id: user.id, action_type: "publish_to_youtube", target_id: publication.id, payload: { youtubeVideoId: result.id }, result: "success" }); return json({ status: "published", youtubeVideoId: result.id });
  } catch (error) { const message = error instanceof Error ? error.message : "Upload selhal."; await admin.from("youtube_publications").update({ status: "failed", error_message: message.slice(0, 1000) }).eq("id", publication.id).eq("user_id", user.id); await admin.from("agent_action_log").insert({ user_id: user.id, action_type: "publish_to_youtube", target_id: publication.id, payload: {}, result: "error", error_message: message }); return json({ error: message }, 502); }
});
